// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvK5hb3oaNhdlmI1B0yHG-hOW_TPKmaGw',
    appId: '1:521890849193:web:6a627e0973b5b38548e4b8',
    messagingSenderId: '521890849193',
    projectId: 'guc-scheduling-app',
    authDomain: 'guc-scheduling-app.firebaseapp.com',
    databaseURL: 'https://guc-scheduling-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'guc-scheduling-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm3j4uQ5yt6cLEj2aLqP-czUrVPbYOMa4',
    appId: '1:521890849193:android:cbe607fb75fafc5248e4b8',
    messagingSenderId: '521890849193',
    projectId: 'guc-scheduling-app',
    databaseURL: 'https://guc-scheduling-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'guc-scheduling-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt4JBdfHP5tpzEfTuPDoJv8z5UiMF1td4',
    appId: '1:521890849193:ios:7e736e9ed8aac67048e4b8',
    messagingSenderId: '521890849193',
    projectId: 'guc-scheduling-app',
    databaseURL: 'https://guc-scheduling-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'guc-scheduling-app.appspot.com',
    iosClientId: '521890849193-praqumn4inugqk13vof9nddbqi8771jf.apps.googleusercontent.com',
    iosBundleId: 'com.example.gucSchedulingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt4JBdfHP5tpzEfTuPDoJv8z5UiMF1td4',
    appId: '1:521890849193:ios:7e736e9ed8aac67048e4b8',
    messagingSenderId: '521890849193',
    projectId: 'guc-scheduling-app',
    databaseURL: 'https://guc-scheduling-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'guc-scheduling-app.appspot.com',
    iosClientId: '521890849193-praqumn4inugqk13vof9nddbqi8771jf.apps.googleusercontent.com',
    iosBundleId: 'com.example.gucSchedulingApp',
  );
}
